export { default as Menus } from "./Menus"
export { default as Anchor1 } from "./Anchor1"
export { default as BrasletiVideo } from "./BrasletiVideo"
export { default as ZavodVideo } from "./ZavodVideo"
export { default as ArctikaVideo } from "./ArctikaVideo"
export { default as AntreVideo } from "./AntreVideo"
export { default as MasterVideo } from "./MasterVideo"
export { default as CrimeaVideo } from "./CrimeaVideo"
